name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
  test:      
    needs: [build]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: sbt test
  assembly:
      needs: [build, test]
      if: success()
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'temurin'
            cache: 'sbt'
        - name: Assembly uber jar
          run: sbt assembly       
          
#         - name: Upload Artifacts
#           uses: actions/upload-artifact@v2
#           with:
#             name: Artifacts
#             path: ./target/scala-3.2.0/ISIQuiz.jar  
          
        - name: Clone Repo with Checkout 
          uses: actions/checkout@v2 
   
#         - name: Download Artifacts
#           uses: actions/download-artifact@v2
#           with:
#             name: Artifacts

        - name: Extract Date
          shell: bash
          id: extract_date
          run: |
            echo "::set-output name=DATE::Release-$(date +%F_%H-%M)"
        - name: Print Output Step
          run: echo ${{ steps.extract_date.outputs.DATE }}
        - name: Deploy
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            git config --global user.name "${{ secrets.NAME }}"
            git config --global user.email "${{ secrets.EMAIL }}"
            TAG="${{ steps.extract_date.outputs.DATE }}"
            MSG="${{ github.event.head_commit.message }}"
            echo $TAG
            hub release create -m "$TAG" "$TAG" || true
            tree
            for f in ./target/scala-3.2.0/*.jar; do
              echo "Delivering file: $f"
              gh release upload "$TAG" "$f" --clobber
              rm $f
            done
          
          
          
          
          
          

