name: Website

on:
  push:
  workflow_dispatch:
    branches: [ "Improve-CI" ]
  # called by another workflow
  workflow_call:
  
jobs:
  CreateArtifactReadme:      
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repo
        uses: actions/checkout@v3
      - name: Print Branch
        run: git branch
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
            README.MD
            
